# Copyright (c) 2014-2022 Kartik Kumar (me@kartikkumar.com)
# Distributed under the MIT License.
# See accompanying file LICENSE or copy at http://opensource.org/licenses/MIT

# This workflow is based off of the GitHub Actions documentation:
# - https://docs.github.com/en/actions

name: run-all-tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.23.x'
      - name: Build CMake project
        run: |
          cmake -S . -B build -DBUILD_TESTING=on
          cmake --build build
      - name: Run tests
        run: make -C build test
